### ISSUE TITLE
I am unable to install the addon.

### ISSUE THREAD

**Issue by Sauron462** [geekprojects/nuTensor#14]
I decided to build the extension manually to run it, but even after cloning the repositories, and running the make script, Firefox marks the XPI as unverified. Is this known and I just have to continually load it temporarily? Or is this unintended behavior?

Using Firefox 83 and trying to install latest version.

**Comment by rany2** [comment]
Hello @Sauron462, 

Yes, it's true that it will keep getting marked as unverified if you choose to build it yourself, however you could have it permanently installed by going to `about:config` and setting `xpinstall.signatures.required` to `false`.

After doing that restart the browser and try to install it from zip file again

**Comment by ghost** [comment]
I don't think `xpinstall.signatures.required` will work on stable release - only beta/dev/nightly.

**Comment by rany2** [comment]
@gwarser It does work on ESR and Debian sid's firefox stable. Most likely you're right because I'm not using Mozilla's official builds.

**Comment by Sauron462** [comment]
Yeah, it doesn't, I've tried that setting before.

**Comment by Sauron462** [comment]
Alright, I set up Dev edition and will use that for now.
