### ISSUE TITLE
Global allow specific hosts or scripts

### ISSUE THREAD

**Issue by Serevinus** [geekprojects/nuTensor#20]
Hi,

A feature I have been missing from uMatrix and now nuTensor is the ability to globally allow certain domains or scripts across all sites. For example reCaptcha, hCaptcha, Cloudflare or jQuery which I trust and am happy to allow across the board.

reCaptcha in particular is a bit of a pain, requiring that you refresh the page two or three times in order to allow all the scripts and iframes, which are irritatingly spread across multiple hostnames.

Is this something that you would be able to implement?

Thanks
J

**Comment by ghost** [comment]
https://github.com/gorhill/uMatrix/wiki/How-to-create-rules-which-apply-everywhere,-on-all-web-sites

**Comment by Serevinus** [comment]
I was not aware of that, thanks
