### ISSUE TITLE
Compiling Failed 

### ISSUE THREAD

**Issue by nutta-git** [geekprojects/nuTensor#7]
**Describe the bug**

When trying to compile nuTensor, multiple errors are shown and the compilation fails 
**To Reproduce**

cd  ~/nuTensor/tools/
sh make-firefox.sh all 
See error
`*** nuTensor.firefox: Creating web store package`
`*** nuTensor.firefox: Copying files`
`bash: ./tools/make-assets.sh: No such file or directory`
`cp: cannot stat './src/*': No such file or directory`
`cp: cannot stat 'platform/chromium/*.js': No such file or directory`
`cp: cannot stat 'platform/chromium/img/*': No such file or directory`
`cp: cannot stat 'LICENSE.txt': No such file or directory`
`cp: cannot stat 'platform/firefox/*.js': No such file or directory`
`cp: cannot stat 'platform/firefox/manifest.json': No such file or directory`
`*** nuTensor.firefox: Generating meta...`
`python3: can't open file 'tools/make-firefox-meta.py': [Errno 2] No such file or directory`
`*** nuTensor.firefox: Creating package...`
`make-firefox.sh: line 29: zip: command not found`
`*** nuTensor.firefox: Package done.`

**Expected behavior**
unTensor should compile 

**Browser (please complete the following information):**
 - OS: Arch Linux
 - Browser: Firefox

**Additional context**

**Comment by DrFlibble** [comment]
You have to run the make scripts from the root of the repo, i.e. tools/make-firefox.sh
